type = "parachain"
name = "Rococo Local Testnet"
para_id = 2001
parachain_rpc_url = "ws://65.108.73.88:9988"
relay_chain_rpc_url = "ws://65.108.73.88:9944"
# client_id = "10-grandpa-0"
channel_whitelist = []
commitment_prefix = "0x6962632f"
private_key = "//Alice"
ss58_version = 49
key_type = "sr25519"
finality_protocol = "Grandpa"