type = "cosmos"
name = "polytope"
rpc_url = "http://127.0.0.1:26657"
grpc_url = "http://127.0.0.1:9090"
websocket_url = "ws://127.0.0.1:26657/websocket"
chain_id = "test-1"
account_prefix = "polytope"
channel_whitelist = []
client_id = "07-tendermint-3"
fee_denom = "stake"
fee_amount = "15000"
gas_limit = 10000000
store_prefix = "0x6962632f"
max_tx_size = 20000000  # a number
keybase =  {Mnemonic = "decorate bright ozone fork gallery riot bus exhaust worth way bone indoor calm squirrel merry zero scheme cotton until shop any excess stage laundry" }
wasm_code_id = "6132314783d515925bff16297eb4e97defc7405efd6a605b60af799592b0fd19"
# 536a8821bcbb153c1838f9ab387c459461b41fdecdcfbcde405f0e8adc459754
# 6132314783d515925bff16297eb4e97defc7405efd6a605b60af799592b0fd19